# Generated by Django 4.0.2 on 2022-07-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', help_text='Enter the blog Post content', max_length=1000),
            preserve_default=False,
        ),
    ]
